/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'academic' : null } |
  { 'event' : null } |
  { 'general' : null } |
  { 'sports' : null };
export interface CreateNoticeRequest {
  'title' : string,
  'date' : string,
  'description' : string,
  'category' : Category,
  'fileUrl' : string,
}
export type DeleteResult = { 'ok' : null } |
  { 'err' : string };
export interface LoginRequest { 'username' : string, 'password' : string }
export type LoginResult = { 'ok' : { 'username' : string, 'role' : Role } } |
  { 'err' : string };
export interface Notice {
  'id' : NoticeId,
  'title' : string,
  'date' : string,
  'createdAt' : Timestamp,
  'createdBy' : string,
  'description' : string,
  'category' : Category,
  'fileUrl' : string,
}
export type NoticeId = bigint;
export type NoticeResult = { 'ok' : Notice } |
  { 'err' : string };
export interface RegisterRequest {
  'username' : string,
  'password' : string,
  'role' : Role,
}
export type RegisterResult = { 'ok' : null } |
  { 'err' : string };
export type Role = { 'admin' : null } |
  { 'student' : null };
export type Timestamp = bigint;
export interface UpdateNoticeRequest {
  'id' : NoticeId,
  'title' : string,
  'date' : string,
  'description' : string,
  'category' : Category,
  'fileUrl' : string,
}
export interface _SERVICE {
  'createNotice' : ActorMethod<[CreateNoticeRequest, string], NoticeResult>,
  'deleteNotice' : ActorMethod<[bigint, string], DeleteResult>,
  'getAllNotices' : ActorMethod<[], Array<Notice>>,
  'getNoticeById' : ActorMethod<[bigint], [] | [Notice]>,
  'login' : ActorMethod<[LoginRequest], LoginResult>,
  'register' : ActorMethod<[RegisterRequest], RegisterResult>,
  'updateNotice' : ActorMethod<[UpdateNoticeRequest, string], NoticeResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];