/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'academic' : IDL.Null,
  'event' : IDL.Null,
  'general' : IDL.Null,
  'sports' : IDL.Null,
});
export const CreateNoticeRequest = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'fileUrl' : IDL.Text,
});
export const NoticeId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Notice = IDL.Record({
  'id' : NoticeId,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'fileUrl' : IDL.Text,
});
export const NoticeResult = IDL.Variant({ 'ok' : Notice, 'err' : IDL.Text });
export const DeleteResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const LoginRequest = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
export const LoginResult = IDL.Variant({
  'ok' : IDL.Record({ 'username' : IDL.Text, 'role' : Role }),
  'err' : IDL.Text,
});
export const RegisterRequest = IDL.Record({
  'username' : IDL.Text,
  'password' : IDL.Text,
  'role' : Role,
});
export const RegisterResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});
export const UpdateNoticeRequest = IDL.Record({
  'id' : NoticeId,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'fileUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'createNotice' : IDL.Func(
      [CreateNoticeRequest, IDL.Text],
      [NoticeResult],
      [],
    ),
  'deleteNotice' : IDL.Func([IDL.Nat, IDL.Text], [DeleteResult], []),
  'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getNoticeById' : IDL.Func([IDL.Nat], [IDL.Opt(Notice)], ['query']),
  'login' : IDL.Func([LoginRequest], [LoginResult], []),
  'register' : IDL.Func([RegisterRequest], [RegisterResult], []),
  'updateNotice' : IDL.Func(
      [UpdateNoticeRequest, IDL.Text],
      [NoticeResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'academic' : IDL.Null,
    'event' : IDL.Null,
    'general' : IDL.Null,
    'sports' : IDL.Null,
  });
  const CreateNoticeRequest = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'fileUrl' : IDL.Text,
  });
  const NoticeId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Notice = IDL.Record({
    'id' : NoticeId,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'fileUrl' : IDL.Text,
  });
  const NoticeResult = IDL.Variant({ 'ok' : Notice, 'err' : IDL.Text });
  const DeleteResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const LoginRequest = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'student' : IDL.Null });
  const LoginResult = IDL.Variant({
    'ok' : IDL.Record({ 'username' : IDL.Text, 'role' : Role }),
    'err' : IDL.Text,
  });
  const RegisterRequest = IDL.Record({
    'username' : IDL.Text,
    'password' : IDL.Text,
    'role' : Role,
  });
  const RegisterResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UpdateNoticeRequest = IDL.Record({
    'id' : NoticeId,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'fileUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'createNotice' : IDL.Func(
        [CreateNoticeRequest, IDL.Text],
        [NoticeResult],
        [],
      ),
    'deleteNotice' : IDL.Func([IDL.Nat, IDL.Text], [DeleteResult], []),
    'getAllNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getNoticeById' : IDL.Func([IDL.Nat], [IDL.Opt(Notice)], ['query']),
    'login' : IDL.Func([LoginRequest], [LoginResult], []),
    'register' : IDL.Func([RegisterRequest], [RegisterResult], []),
    'updateNotice' : IDL.Func(
        [UpdateNoticeRequest, IDL.Text],
        [NoticeResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };