/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type NoticeResult = {
    __kind__: "ok";
    ok: Notice;
} | {
    __kind__: "err";
    err: string;
};
export type RegisterResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Timestamp = bigint;
export interface LoginRequest {
    username: string;
    password: string;
}
export interface RegisterRequest {
    username: string;
    password: string;
    role: Role;
}
export interface Notice {
    id: NoticeId;
    title: string;
    date: string;
    createdAt: Timestamp;
    createdBy: string;
    description: string;
    category: Category;
    fileUrl: string;
}
export type DeleteResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type LoginResult = {
    __kind__: "ok";
    ok: {
        username: string;
        role: Role;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface UpdateNoticeRequest {
    id: NoticeId;
    title: string;
    date: string;
    description: string;
    category: Category;
    fileUrl: string;
}
export type NoticeId = bigint;
export interface CreateNoticeRequest {
    title: string;
    date: string;
    description: string;
    category: Category;
    fileUrl: string;
}
export enum Category {
    academic = "academic",
    event = "event",
    general = "general",
    sports = "sports"
}
export enum Role {
    admin = "admin",
    student = "student"
}
export interface backendInterface {
    createNotice(req: CreateNoticeRequest, adminUsername: string): Promise<NoticeResult>;
    deleteNotice(id: bigint, adminUsername: string): Promise<DeleteResult>;
    getAllNotices(): Promise<Array<Notice>>;
    getNoticeById(id: bigint): Promise<Notice | null>;
    login(req: LoginRequest): Promise<LoginResult>;
    register(req: RegisterRequest): Promise<RegisterResult>;
    updateNotice(req: UpdateNoticeRequest, adminUsername: string): Promise<NoticeResult>;
}
import type { Category as _Category, CreateNoticeRequest as _CreateNoticeRequest, DeleteResult as _DeleteResult, LoginResult as _LoginResult, Notice as _Notice, NoticeId as _NoticeId, NoticeResult as _NoticeResult, RegisterRequest as _RegisterRequest, RegisterResult as _RegisterResult, Role as _Role, Timestamp as _Timestamp, UpdateNoticeRequest as _UpdateNoticeRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createNotice(arg0: CreateNoticeRequest, arg1: string): Promise<NoticeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotice(to_candid_CreateNoticeRequest_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_NoticeResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotice(to_candid_CreateNoticeRequest_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_NoticeResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteNotice(arg0: bigint, arg1: string): Promise<DeleteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNotice(arg0, arg1);
                return from_candid_DeleteResult_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNotice(arg0, arg1);
            return from_candid_DeleteResult_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotices(): Promise<Array<Notice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotices();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotices();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNoticeById(arg0: bigint): Promise<Notice | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoticeById(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoticeById(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: LoginRequest): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0);
                return from_candid_LoginResult_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0);
            return from_candid_LoginResult_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async register(arg0: RegisterRequest): Promise<RegisterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.register(to_candid_RegisterRequest_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_RegisterResult_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(to_candid_RegisterRequest_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_RegisterResult_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNotice(arg0: UpdateNoticeRequest, arg1: string): Promise<NoticeResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNotice(to_candid_UpdateNoticeRequest_n25(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_NoticeResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNotice(to_candid_UpdateNoticeRequest_n25(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_NoticeResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_DeleteResult_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeleteResult): DeleteResult {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_NoticeResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoticeResult): NoticeResult {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Notice_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notice): Notice {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_RegisterResult_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisterResult): RegisterResult {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Notice]): Notice | null {
    return value.length === 0 ? null : from_candid_Notice_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    role: _Role;
}): {
    username: string;
    role: Role;
} {
    return {
        username: value.username,
        role: from_candid_Role_n18(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NoticeId;
    title: string;
    date: string;
    createdAt: _Timestamp;
    createdBy: string;
    description: string;
    category: _Category;
    fileUrl: string;
}): {
    id: NoticeId;
    title: string;
    date: string;
    createdAt: Timestamp;
    createdBy: string;
    description: string;
    category: Category;
    fileUrl: string;
} {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        category: from_candid_Category_n9(_uploadFile, _downloadFile, value.category),
        fileUrl: value.fileUrl
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    academic: null;
} | {
    event: null;
} | {
    general: null;
} | {
    sports: null;
}): Category {
    return "academic" in value ? Category.academic : "event" in value ? Category.event : "general" in value ? Category.general : "sports" in value ? Category.sports : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        username: string;
        role: _Role;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        username: string;
        role: Role;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n17(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    student: null;
}): Role {
    return "admin" in value ? Role.admin : "student" in value ? Role.student : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Notice;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Notice;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Notice_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notice>): Array<Notice> {
    return value.map((x)=>from_candid_Notice_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateNoticeRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateNoticeRequest): _CreateNoticeRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterRequest_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterRequest): _RegisterRequest {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateNoticeRequest_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateNoticeRequest): _UpdateNoticeRequest {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: string;
    description: string;
    category: Category;
    fileUrl: string;
}): {
    title: string;
    date: string;
    description: string;
    category: _Category;
    fileUrl: string;
} {
    return {
        title: value.title,
        date: value.date,
        description: value.description,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        fileUrl: value.fileUrl
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    password: string;
    role: Role;
}): {
    username: string;
    password: string;
    role: _Role;
} {
    return {
        username: value.username,
        password: value.password,
        role: to_candid_Role_n22(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: NoticeId;
    title: string;
    date: string;
    description: string;
    category: Category;
    fileUrl: string;
}): {
    id: _NoticeId;
    title: string;
    date: string;
    description: string;
    category: _Category;
    fileUrl: string;
} {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        description: value.description,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        fileUrl: value.fileUrl
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    student: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.student ? {
        student: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    academic: null;
} | {
    event: null;
} | {
    general: null;
} | {
    sports: null;
} {
    return value == Category.academic ? {
        academic: null
    } : value == Category.event ? {
        event: null
    } : value == Category.general ? {
        general: null
    } : value == Category.sports ? {
        sports: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
